
export enum VisaSituation {
  F1_PRE_ARRIVAL = 'F-1 – Before starting school',
  F1_STUDY = 'F-1 – During study',
  F1_OPT_APPLY = 'F-1 – OPT application phase',
  F1_OPT_ACTIVE = 'F-1 – During OPT',
  OTHER = 'Other / not sure'
}

export enum UserIntent {
  EMAIL = 'Understand an email',
  OPT = 'Check OPT requirements',
  GENERAL = 'General instructions',
}

export type RiskLevel = 'Low' | 'Medium' | 'High';
export type DueCategory = 'today' | 'this_week' | 'before_program_end' | 'after_approval' | 'unspecified';

export interface ChecklistItem {
  id: string; // Unique ID generated by frontend after receiving data
  category: string;
  title: string;
  description: string;
  status: 'todo' | 'in-progress' | 'done';
  dueCategory?: DueCategory;
  dueLabel?: string;
  actor?: string; // e.g. "Student", "DSO", "USCIS"
}

export interface RiskAssessment {
  riskLevel: RiskLevel;
  urgencyLabel: string;
  summary: string;
}

export interface SafetyTerm {
  term: string;
  definition: string;
}

export interface DsoEmailDraft {
  subject: string;
  body: string;
}

export interface AnalysisResult {
  riskAssessment?: RiskAssessment;
  summary: string[]; // Generic summary (English)
  koreanSummary?: string[]; // Optional Korean summary
  detailedExplanation: string;
  simpleEnglishNotes: string;
  checklist: Omit<ChecklistItem, 'id' | 'status'>[]; 
  safetyTerms: SafetyTerm[];
  dsoEmailDraft?: DsoEmailDraft;
  dsoQuestions?: string[]; // List of suggested questions
}

export type Locale = 'en' | 'ko' | 'zh' | 'hi' | 'ja';

export interface AppState {
  view: 'landing' | 'workspace';
  intent: UserIntent;
  situation: VisaSituation;
  inputText: string;
  isAnalyzing: boolean;
  result: AnalysisResult | null;
  checklistState: ChecklistItem[]; 
  error: string | null;
  locale: Locale;
}
