export enum VisaSituation {
  F1_PRE_ARRIVAL = 'F-1 – Pre-arrival (Before coming to US)',
  F1_STUDY = 'F-1 – During study (Current student)',
  F1_OPT_APPLY = 'F-1 – OPT application phase',
  F1_OPT_ACTIVE = 'F-1 – During OPT (Working)',
  OTHER = 'Other / Not Sure'
}

export interface ChecklistItem {
  id: string; // Unique ID generated by frontend after receiving data
  category: string;
  title: string;
  description: string;
  status: 'todo' | 'in-progress' | 'done';
}

export interface SafetyTerm {
  term: string;
  definition: string;
}

export interface AnalysisResult {
  summaryKorean: string[];
  detailedExplanation: string;
  simpleEnglishNotes: string;
  checklist: Omit<ChecklistItem, 'id' | 'status'>[]; // API returns raw items
  safetyTerms: SafetyTerm[];
}

export interface AppState {
  situation: VisaSituation;
  inputText: string;
  isAnalyzing: boolean;
  result: AnalysisResult | null;
  checklistState: ChecklistItem[]; // Local state for checklist interaction
  error: string | null;
}
