
export enum VisaSituation {
  F1_PRE_ARRIVAL = 'F-1 – Before starting school',
  F1_STUDY = 'F-1 – During study',
  F1_OPT_APPLY = 'F-1 – OPT application phase',
  F1_OPT_ACTIVE = 'F-1 – During OPT',
  OTHER = 'Other / not sure'
}

export enum UserIntent {
  EMAIL = 'Understand an email',
  OPT = 'Check OPT requirements',
  GENERAL = 'General instructions',
}

export type RiskLevel = 'Low' | 'Medium' | 'High';
export type DueCategory = 'today' | 'this_week' | 'before_program_end' | 'after_approval' | 'unspecified';

export interface ChecklistItem {
  id: string; // Unique ID generated by frontend after receiving data
  category: string;
  title: string;
  description: string;
  status: 'todo' | 'in-progress' | 'done';
  dueCategory?: DueCategory;
  dueLabel?: string;
  actor?: string; // e.g. "Student", "DSO", "USCIS"
  priority?: 'high' | 'medium' | 'low';
  timeBucket?: 'today' | 'this_week' | 'later' | 'unspecified';
}

export interface RiskAssessment {
  riskLevel: RiskLevel;
  urgencyLabel: string;
  summary: string;
}

export interface SafetyTerm {
  term: string;
  definition: string;
}

export interface DsoEmailDraft {
  subject: string;
  body: string;
}

export interface AnalysisResult {
  riskAssessment?: RiskAssessment;
  summary: string[]; // Generic summary (English)
  koreanSummary?: string[]; // Optional Korean summary
  detailedExplanation: string;
  simpleEnglishNotes: string;
  checklist: Omit<ChecklistItem, 'id' | 'status'>[]; 
  safetyTerms: SafetyTerm[];
  dsoEmailDraft?: DsoEmailDraft;
  dsoQuestions?: string[]; // List of suggested questions
  topic?: string; // e.g. "pre_completion_opt"
  topicLabel?: string; // e.g. "Pre-completion OPT"
}

export interface FollowUpQAEntry {
  id: string;
  question: string;
  answer: string;
  timestamp: number;
}

export type Locale = 'en' | 'ko' | 'zh' | 'hi' | 'ja';

// New types for multilingual support
export type SupportedLanguage = "none" | "ko" | "zh-CN" | "hi" | "ja";

export interface TranslatedAnalysis {
  language: SupportedLanguage;
  riskCard?: {
    riskLevel: string; // Translated level name
    urgencyLabel: string; // Translated urgency
    summary: string; // Translated summary
  };
  summaryBullets: string[];
  detailedExplanation: string;
  simpleEnglishNote?: string;
  checklistItems: { id: string; title: string; description: string }[];
  keyTerms?: { term: string; explanation: string }[]; // term kept in EN, explanation translated
  dsoEmailNote?: string; // Explanation of the email draft
}

export interface AppState {
  view: 'landing' | 'workspace';
  intent: UserIntent;
  situation: VisaSituation;
  inputText: string;
  isAnalyzing: boolean;
  result: AnalysisResult | null;
  checklistState: ChecklistItem[]; 
  error: string | null;
  locale: Locale;
  // Translation state
  translationLanguage: SupportedLanguage;
  translationResult: TranslatedAnalysis | null;
  isTranslating: boolean;
}
